[package]
name = "mac_desktop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.8"
client-backend = { path = "../client-backend" }
iced = { version = "0.10.0", features = ["tokio"] }
serde = "1.0.192"
serde_json = "1.0.108"
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
