
comment_width = 80
wrap_comments = true
combine_control_expr = true
fn_single_line = true
imports_granularity = "Crate"
overflow_delimited_expr = true
group_imports = "StdExternalCrate"
struct_lit_single_line = true
use_field_init_shorthand = true
